const WORDS = [
  { ru: "Принц", en: "Prince" },
  { ru: "Принцесса", en: "Princess" },
  { ru: "Король", en: "King" },
  { ru: "Королева", en: "Queen" },
  { ru: "Корона", en: "Crown" },
  { ru: "Замок", en: "Castle" },
  { ru: "Карета", en: "Carriage" },
  { ru: "Трон", en: "Throne" },
  { ru: "Версаль", en: "Versailles" },
  { ru: "Золотая монета", en: "Gold coin" },
  { ru: "Хрустальная туфелька", en: "Glass slipper" },
  { ru: "Волшебная палочка", en: "Magic wand" },
  { ru: "Рыцарь", en: "Knight" },
  { ru: "Дракон", en: "Dragon" },
  { ru: "Дворец", en: "Palace" },
  { ru: "Меч", en: "Sword" },
  { ru: "Щит", en: "Shield" },
  { ru: "Конь", en: "Horse" },
  { ru: "Королевский бал", en: "Royal ball" },
  { ru: "Фея", en: "Fairy" },
  { ru: "Ведьма", en: "Witch" },
  { ru: "Гном", en: "Dwarf" },
  { ru: "Поцелуй", en: "Kiss" },
  { ru: "Магия", en: "Magic" },
  { ru: "Кольцо", en: "Ring" },
  { ru: "Королевский стражник", en: "Royal guard" },
  { ru: "Башня", en: "Tower" },
  { ru: "Подземелье", en: "Dungeon" },
  { ru: "Полночь", en: "Midnight" },
  { ru: "Коронация", en: "Coronation" },
  { ru: "Золушка", en: "Cinderella" },
  { ru: "Белоснежка", en: "Snow White" },
  { ru: "Ариэль", en: "Ariel" },
  { ru: "Белль", en: "Belle" },
  { ru: "Жасмин", en: "Jasmine" },
  { ru: "Аврора", en: "Aurora" },
  { ru: "Рапунцель", en: "Rapunzel" },
  { ru: "Эльза", en: "Elsa" },
  { ru: "Мулан", en: "Mulan" },
  { ru: "Покахонтас", en: "Pocahontas" },
  { ru: "Мерида", en: "Merida" },
  { ru: "Моана", en: "Moana" },
  { ru: "Принцесса Фиона", en: "Princess Fiona" },
  { ru: "Дюймовочка", en: "Thumbelina" },
  { ru: "Аладдин", en: "Aladdin" },
  { ru: "Тарзан", en: "Tarzan" },
  { ru: "Шрек", en: "Shrek" },
  { ru: "Геркулес", en: "Hercules" },
  { ru: "Симба", en: "Simba" },
  { ru: "Чудовище", en: "Beast" },
  { ru: "Джинн", en: "Genie" },
  { ru: "Пиноккио (Буратино)", en: "Pinocchio" },
  { ru: "Питер Пэн", en: "Peter Pan" },
  { ru: "Робин Гуд", en: "Robin Hood" },
  { ru: "Холодное сердце", en: "Frozen" },
  { ru: "Принцесса и лягушка", en: "The Princess and the Frog" },
  { ru: "Алиса в Стране чудес", en: "Alice in Wonderland" },
  { ru: "Красавица и Чудовище", en: "Beauty and the Beast" },
  { ru: "Спящая красавица", en: "Sleeping Beauty" },
  { ru: "Белоснежка и семь гномов", en: "Snow White and the Seven Dwarfs" },
  { ru: "Король Лев", en: "The Lion King" },
  { ru: "Малефисента", en: "Maleficent" },
  { ru: "Лебединое озеро", en: "Swan Lake" },
  { ru: "Как приручить дракона", en: "How to Train Your Dragon" },
  { ru: "Принцесса Диана (Англия)", en: "Princess Diana (England)" },
  { ru: "Принц Гарри (Англия)", en: "Prince Harry (England)" },
  { ru: "Королева Елизавета (Англия)", en: "Queen Elizabeth (England)" },
  { ru: "Отравленное яблоко", en: "Poisoned apple" },
  { ru: "Ковер-самолет", en: "Magic carpet" },
  { ru: "Красная роза", en: "Red rose" },
  { ru: "Вальс", en: "Waltz" },
  { ru: "Злая мачеха", en: "Wicked stepmother" },
  { ru: "Принц-лягушка", en: "Frog prince" },
  { ru: "Сундук с сокровищами", en: "Treasure chest" },
  { ru: "Пират", en: "Pirate" },
  { ru: "группа Queen", en: "the band Queen" },
  { ru: "Рыцари круглого стола", en: "Knights of the Round Table" },
  { ru: "Проклятье", en: "Curse" },
  { ru: "Наследник престола", en: "Heir to the throne" },
  { ru: "Дворецкий", en: "Butler" },
  { ru: "Волшебное зеркало", en: "The Magic Mirror" },
  { ru: "Единорог", en: "Unicorn" },
  { ru: "Свадьба", en: "Wedding" },
  { ru: "Королевство", en: "Kingdom" },
  { ru: "Сказка", en: "Fairy tale" },
  { ru: "Пьяная Принцесса", en: "Drunken Princess" },
  { ru: "Тронный зал", en: "Throne Room" },
  { ru: "Поединок (или дуэль)", en: "Duel" },
  { ru: "Заклинание", en: "Spell" },
  { ru: "Тыква", en: "Pumpkin" },
  { ru: "Золото", en: "Gold" },
  { ru: "Алмаз", en: "Diamond" },
  { ru: "Сокровища", en: "Treasures" },
  { ru: "Письмо", en: "Letter" },
  { ru: "Флаг", en: "Flag" },
  { ru: "Королевский Советник", en: "Royal Advisor" },
  { ru: "Шут", en: "Jester" },
  { ru: "Фонтан", en: "Fountain" },
  { ru: "Лабиринт", en: "Maze" },
  { ru: "Феерверк (или салют)", en: "Fireworks" },
  { ru: "Слуга", en: "Servant" },
  { ru: "Посол", en: "Ambassador" },
  { ru: "Королевская спальня", en: "The Royal Bedroom" },
  { ru: "Падающая звезда", en: "Shooting star" },
];

export default WORDS;
